# coding: utf-8
# -*- mode: ruby -*-

Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.1"

  # disable auto update Guest Addition
  config.vbguest.auto_update = false
  config.vm.network "private_network", ip: "10.20.30.50"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.provision "shell", path: "./build-php7.sh"
end
